name: Artemis control CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MONGO_DB_URL: mongodb://localhost/artemisControl
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        name: install pnpm
        with:
          version: 8
      - name: "build client"
        run: "cd client && pnpm install && pnpm run build"
      - name: "Setup MongoDB"
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: "5.0"
      - name: "Run tests"
        run: "cd server && pnpm install && pnpm run test"
